### ISSUE TITLE
"Try it Online" goes to wrong link

### ISSUE THREAD

**Issue by MasterOfTheTiger** [Nanomotion/xor#11]
The "Try it online" button in the README file goes [here](https://xor-editor.github.io/xor) (which returns 404), but it should go the same place as the website link in the description. (https://nanomotion.github.io/xor/)

**Comment by Narulacodes** [comment]
I have Made A Pr to fix this.
@Nanomotion

**Comment by Nanomotion** [comment]
Thanks @Narulacodes for the PR.

**Comment by Narulacodes** [comment]
np
